{% set name = "backports.csv" %}
{% set version = "1.0.7" %}
{% set sha256sum = "1277dfff73130b2e106bf3dd347adb3c5f6c4340882289d88f31240da92cbd6d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - backports.csv

about:
  home: https://github.com/ryanhiebert/backports.csv/
  license: PSFL 2
  license_family: PSF
  license_file: LICENSE.rst
  summary: Backport of Python 3's csv module for Python 2
  doc_url: "https://pypi.org/project/backports.csv/"
  dev_url: "https://github.com/ryanhiebert/backports.csv"


extra:
  recipe-maintainers:
    - mxr-conda
    - rmax
    - oblute
